version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker-compose"
    directories:
      - "/elasticsearch/**"
      - "/grafana/**"
      - "/jaeger/**"
      - "/kafka/**"
      - "/kibana/**"
      - "/mongo/**"
      - "/mosquitto/**"
      - "/postgresql/**"
      - "/prometheus/**"
      - "/rabbitmq/**"
      - "/redis/**"
      - "/vault/**"
    schedule:
      interval: "weekly"
      day: "sunday"
