x-postgres-common: &postgres-common
  image: docker.io/postgres:18.2
  restart: unless-stopped
  environment:
    POSTGRES_USER: "user"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "database"
  healthcheck:
    test:
      - "CMD-SHELL"
      - |
        pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    <<: *postgres-common

volumes:
  postgres-data:
