x-rabbitmq-common: &rabbitmq-common
  image: docker.io/rabbitmq:4.2.2-management
  restart: unless-stopped
  environment:
    RABBITMQ_DEFAULT_USER: "user"
    RABBITMQ_DEFAULT_PASS: "password"
  healthcheck:
    test:
      - "CMD"
      - "rabbitmq-diagnostics"
      - "ping"
    interval: 10s
    timeout: 5s
    retries: 3

services:
  rabbitmq:
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    <<: *rabbitmq-common

volumes:
  rabbitmq-data:
